### ISSUE TITLE
mutliple chains in function

### ISSUE THREAD

**Issue by emilsivervik** [chrisrosenlind/scb#2]
https://github.com/chrisrosenlind/scb/blob/0b8e50808387b9dae0068a3eef79c2f007445a14/index.js#L45-L56

Hello it's Emil again, 

I've been reviewing your API again and I'm just wondering why you are using multiple chains inside the  `call` function. Isn't it bad practice using a chain inside a chain? I mean you are already getting a chain from `this.api.request` so you don't really need to create a new one with `new Promise`?

**Comment by chrisrosenlind** [comment]
Hi Emil

Thank you for your issue regarding the multiple chains. As per latest commit, this issue is no longer present, hence why I will close this issue.
